import Layout from '@/components/layout/Layout';
import Head from 'next/head';
const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  url: 'https://www.homehada.com/',
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: 'https://www.homehada.com/search?q={search_term_string}',
    },
    'query-input': 'required name=search_term_string',
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </Head>
      <Layout>
        <div>노토산스 테스트 </div>
      </Layout>
    </>
  );
}
